package:
  name: openmatrix
  version: "0.2.3"

source:
  fn: OpenMatrix-0.2.3.zip
  url: https://pypi.python.org/packages/source/O/OpenMatrix/OpenMatrix-0.2.3.zip
  md5: e612884fb3b1317b8ec01fca4b79ece5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - openmatrix = openmatrix:main
    #
    # Would create an entry point called openmatrix that calls openmatrix.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pytables >=3.0
    - numpy >=1.5.0

  run:
    - python
    - pytables >=3.0
    - numpy >=1.5.0

test:
  # Python imports
  imports:
    - openmatrix

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://sites.google.com/site/openmodeldata
  license: Apache Software License
  summary: 'OMX, the open matrix data format.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
