# trip_mode_choice.yaml

SPEC: trip_mode_choice.csv
COEFFICIENTS: trip_mode_choice_coefficients.csv
COEFFICIENT_TEMPLATE: trip_mode_choice_coefficients_template.csv

LOGIT_TYPE: NL

NESTS:
  name: root
  coefficient: 1.00
  alternatives:
      - name: AUTO
        coefficient: 0.72
        alternatives:
            - DRIVEALONE
            - SHARED2
            - SHARED3
      - name: NONMOTORIZED
        coefficient: 0.72
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  0.72
        alternatives:
            - name: WALKACCESS
              coefficient: 0.5
              alternatives:
              - WALK_AB
              - WALK_BM
              - WALK_MR
              - WALK_CR
            - name: PNRACCESS
              coefficient: 0.5
              alternatives:
              - PNR_AB
              - PNR_BM
              - PNR_MR
              - PNR_CR
            - name: KNRACCESS
              coefficient: 0.5
              alternatives:
              - KNR_AB
              - KNR_BM
              - KNR_MR
              - KNR_CR
      - name: SCHOOL_BUS
        coefficient: 0.72
        alternatives:
          - SCHOOLBUS
      - name: RIDEHAIL
        coefficient: 0.36
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED

CONSTANTS:
  orig_col_name: origin
  dest_col_name: destination
  walkThresh: 1.00
  walktimelong_multiplier: 5 
  biketimelong_multiplier: 5
  xfers_wlk_multiplier: 5
  xfers_drv_multiplier: 15
  density_index_multiplier: -5
  I_MODE_MAP:
    DRIVEALONE: 1
    SHARED2: 2
    SHARED3: 3
    WALK: 4
    BIKE: 5
    WALK_AB: 6
    WALK_BM: 7
    WALK_MR: 8
    WALK_CR: 9
    PNR_AB: 10
    PNR_BM: 11
    PNR_MR: 12
    PNR_CR: 13
    KNR_AB: 14
    KNR_BM: 15
    KNR_MR: 16
    KNR_CR: 17
    SCHOOLBUS: 18
    TAXI: 19
    TNC_SINGLE: 20
    TNC_SHARED: 21
  I_SOV_MODES: [1]
  I_SR2_MODES: [2]
  I_SR3P_MODES: [3]
  I_AUTO_MODES: [1, 2, 3]
  I_WALK_MODE: 4
  I_BIKE_MODE: 5
  I_WALK_TRANSIT_MODES: [6,7,8,9]
  I_DRIVE_TRANSIT_MODES: [10,11,12,13,14,15,16,17]
  I_PNR_TRANSIT_MODES: [10,11,12,13]
  I_KNR_TRANSIT_MODES: [14,15,16,17]
  I_AB_MODES: [6,10,14]
  I_BM_MODES: [7,11,15]
  I_MR_MODES: [8,12,16]
  I_CR_MODES: [9,13,17]  
  I_SCHOOLBUS_MODE: [18]
  I_RIDE_HAIL_MODES: [19, 20, 21]
  Taxi_waitTime_mean:
    1: 5.5
    2: 9.5
    3: 13.3
    4: 17.3
    5: 26.5
  Taxi_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  

# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: trip_mode_choice_annotate_trips_preprocessor
  DF: df
  TABLES:
    - land_use
    - tours

#  - SPEC: trip_mode_choice_annotate_trips_preprocessor2
#    DF: df
#    TABLES:
#      - land_use

# to reduce memory needs filter chooser table to these fields
TOURS_MERGED_CHOOSER_COLUMNS:
  - hhsize
  - age
  - auto_ownership
  - number_of_participants
  - tour_category
  - parent_tour_id
  - tour_mode
  - duration
  - value_of_time
  - tour_type
  - free_parking_at_work


MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
