
enable: False

bundles:
  - tour_scheduling_probabilistic
  - tour_od_choice
  - tour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_scheduling
  - trip_mode_choice

# NOTE: survey table indices must match 1-to-1 with input tables specified in
# settings.yaml. It is recommended to use the same files in both places, but
# this means the trip_id's in the survey data must have been created via the
# abm.models.util.canonical_ids module.
survey_tables:
  households:
    file_name: households_survey.csv
    index_col: household_id
  persons:
    file_name:  persons_survey.csv
    index_col: person_id
  tours:
    file_name:  tours_survey.csv
    index_col: tour_id
  trips:
    file_name:  trips_survey.csv
    index_col: trip_id

estimation_table_recipes:

  interaction_sample_simulate:
    omnibus_tables:
      choosers_combined:
        - choices
        - override_choices
        - choosers
      alternatives_combined:
        - interaction_sample_alternatives
        - interaction_expression_values
    omnibus_tables_append_columns: [choosers_combined]

  interaction_simulate:
    omnibus_tables:
      choosers_combined:
        - choices
        - override_choices
        - choosers
    omnibus_tables_append_columns: [choosers_combined]

  simple_simulate:
    omnibus_tables:
      values_combined:
        - choices
        - override_choices
        - expression_values
        - choosers
    omnibus_tables_append_columns: [values_combined]

  cdap_simulate:
    omnibus_tables:
      values_combined:
        - choices
        - override_choices
        - choosers
    omnibus_tables_append_columns: [values_combined]

  simple_probabilistic:
    omnibus_tables:
      values_combined:
        - choices
        - override_choices
        - choosers
        - probs
    omnibus_tables_append_columns: [values_combined]


model_estimation_table_types:
  tour_scheduling_probabilistic: simple_probabilistic
  tour_od_choice: interaction_sample_simulate
  school_location: interaction_sample_simulate
  workplace_location:  interaction_sample_simulate
  auto_ownership: simple_simulate
  free_parking: simple_simulate
  cdap: cdap_simulate
  mandatory_tour_frequency: simple_simulate
  mandatory_tour_scheduling_work: interaction_sample_simulate
  mandatory_tour_scheduling_school: interaction_sample_simulate
  joint_tour_frequency: simple_simulate
  joint_tour_composition: simple_simulate
  joint_tour_participation: simple_simulate
  joint_tour_destination: interaction_sample_simulate
  joint_tour_scheduling: interaction_sample_simulate
  non_mandatory_tour_frequency: interaction_simulate
  non_mandatory_tour_destination: interaction_sample_simulate
  non_mandatory_tour_scheduling: interaction_sample_simulate
  tour_mode_choice: simple_simulate
  atwork_subtour_frequency: simple_simulate
  atwork_subtour_destination: interaction_sample_simulate
  atwork_subtour_scheduling: interaction_sample_simulate
  atwork_subtour_mode_choice: simple_simulate
  stop_frequency: simple_simulate
  trip_purpose: simple_probabilistic
  trip_destination: interaction_sample_simulate
  trip_scheduling: simple_probabilistic
  trip_mode_choice: simple_simulate
