SPEC: trip_mode_choice.csv
COEFFICIENTS: trip_mode_choice_coefficients.csv
COEFFICIENT_TEMPLATE: trip_mode_choice_coefficients_template.csv

tvpb_mode_path_types:
  WALK_TRANSIT: WTW

LOGIT_TYPE: NL

NESTS:
  name: root
  coefficient: 1.00
  alternatives:
      - name: AUTO
        coefficient: 0.50
        alternatives:
            - DRIVEALONE
            - SHARED2
            - SHARED3
      - name: NONMOTORIZED
        coefficient: 0.50
        alternatives:
          - WALK
      - name: TRANSIT
        coefficient:  0.50
        alternatives:
          - WALK_TRANSIT
      - name: RIDEHAIL
        coefficient: 0.50
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED

CONSTANTS:
  orig_col_name: origin
  dest_col_name: destination
  PERIODS_PER_HOUR: 2
  time_distrib_mean_work: 1.0
  time_distrib_stddev_work: 0.7
  time_distrib_mean_nonwork: 1.0
  time_distrib_stddev_nonwork: 0.6
  cost_per_mile_fuel: 12.3  # from parametersByYear.csv, depends on simulation year
  cost_per_mile_maint: 7  # from parametersByYear.csv, depends on simulation year
  cost_share_s2: 2
  cost_share_s3: 3
  work_dist_coef: -8.6
  other_dist_coef: -4.9
  vot_threshold_low: 8.81
  vot_threshold_med: 18.00
  vot_bin_idx_to_skim_label:
    1: L
    2: M
    3: H
  max_walk_time: 60
  taxi_base_fare: 2.20
  taxi_cost_per_mile: 2.30
  taxi_cost_per_minute: 0.10
  tnc_single_base_fare: 2.20
  tnc_single_cost_per_mile: 1.33
  tnc_single_cost_per_minute: 0.24
  tnc_single_cost_minimum: 7.20
  tnc_shared_base_fare: 2.20
  tnc_shared_cost_per_mile: 0.44
  tnc_shared_cost_per_minute: 0.08
  tnc_shared_cost_minimum: 3.00
  tnc_shared_ivt_factor: 1.25
  tnc_single_wait_time_mean_by_density:
    1: 10.3
    2: 8.5
    3: 8.4
    4: 6.3
    5: 4.7
  tnc_single_wait_time_sd_by_density:
    1: 4.1
    2: 4.1
    3: 4.1
    4: 4.1
    5: 4.1
  tnc_shared_wait_time_mean_by_density:
    1: 15.0
    2: 15.0
    3: 11.0
    4: 8.0
    5: 7.0
  tnc_shared_wait_time_sd_by_density:
    1: 4.1
    2: 4.1
    3: 4.1
    4: 4.1
    5: 4.1
  taxi_wait_time_mean_by_density:
    1: 26.5
    2: 17.3
    3: 13.3
    4: 9.5
    5: 5.5
  taxi_wait_time_sd_by_density:
    1: 6.4
    2: 6.4
    3: 6.4
    4: 6.4
    5: 6.4
  wait_time_distribution_by_density_breaks:
    - 500
    - 2000
    - 5000
    - 15000

TVPB_recipe: trip_mode_choice
use_TVPB_constants: False

# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: trip_mode_choice_annotate_trips_preprocessor
  DF: df
  TABLES:
    - land_use
    - tours

# to reduce memory needs filter chooser table to these fields
TOURS_MERGED_CHOOSER_COLUMNS:
  - tour_type
  - tour_mode
  - stop_frequency
  - demographic_segment
  - duration
  - pass_type

MODE_CHOICE_LOGSUM_COLUMN_NAME: trip_mode_choice_logsum
