os: linux
language: python

env:
  global:
  - TEST_ENV=activitysim-test

jobs:
  include:
    # Add new TEST_SUITE jobs as needed via Travis build matrix expansion
    # define an alternative TEST_ENV to add special dependencies for particular tests
    # Test suites are arranged in groups; all tests in a group must pass before
    # the next stage group can begin.

    - stage: Core Functionality
      env: TEST_SUITE=activitysim/abm/models
    - env: TEST_SUITE=activitysim/abm/test
    - env: TEST_SUITE=activitysim/cli
    - env: TEST_SUITE=activitysim/core

    - stage: Examples
      name: "Gondor Example"
      env: TEST_SUITE=activitysim/examples/example_gondor/test
    - name: "Arnor Example"
      env: TEST_SUITE=activitysim/examples/example_arnor/test
    - name: "Multizone Example"
      env: TEST_SUITE=activitysim/examples/example_multiple_zone/test
    - name: "Marin Example"
      env: TEST_SUITE=activitysim/examples/example_marin/test
    - name: "ARC Example"
      env: TEST_SUITE=activitysim/examples/example_arc/test
    - name: "SEMCOG Example"
      env: TEST_SUITE=activitysim/examples/example_semcog/test
    - name: "PSRC Example"
      env: TEST_SUITE=activitysim/examples/example_psrc/test
    - name: "SANDAG Example"
      env: TEST_SUITE=activitysim/examples/example_sandag/test
    - name: "SANDAG Cross-Border Example"
      env: TEST_SUITE=activitysim/examples/example_sandag_xborder/test

    - stage: Estimation Mode
      name: "Larch Test"
      env: TEST_SUITE=activitysim/estimation/test/test_larch_estimation.py TEST_ENV="activitysim-test-larch"

    - stage: Deployment
      name: Documentation
      env: TEST_ENV="activitysim-test-larch"
      script:
        - coveralls
        # Build docs
        - mamba install sphinx numpydoc
        - conda install -c conda-forge sphinx_rtd_theme==0.5.2
        - cd docs
        - make clean
        - make html
        - touch _build/html/.nojekyll
      deploy:
        - provider: pages
          local_dir: docs/_build/html
          skip_cleanup: true
          github_token: $GH_TOKEN  # Set in the settings page of the repository, as a secure variable
          keep_history: true
          on:
            branch: master
    - name: "PyPI Deployment"
      script: skip     # do not want to rerun any tests
      deploy:
        - provider: pypi
          username: "__token__"
          password: "$PYPI_AUTH_TOKEN"  # Set in the settings page of the repository, as a secure variable
          skip_existing: true
          on:
            branch: [ master ]

python:
  - '3.9'

install:
- wget -O Mambaforge.sh https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-$(uname)-$(uname -m).sh
- bash Mambaforge.sh -b -p $HOME/miniconda
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- mamba update -q mamba
- mamba info -a
# write travis python version into selected test environment definition file
- sed -e "s/\${TRAVIS_PYTHON_VERSION}/${TRAVIS_PYTHON_VERSION}/" conda-environments/${TEST_ENV}.yml > conda-env.yml
# create test environment in one pass
- mamba env create -n asimtest --file conda-env.yml
- conda activate asimtest
- pip install .
- pip freeze

script:
# This is the "default" script used for each test suite, unless overridden with a "script" in the jobs above.
# build 2 and 3 zone test data twice since the Python test code on Linux sees these as different locations
- python activitysim/examples/example_multiple_zone/scripts/two_zone_example_data.py
- python activitysim/examples/example_multiple_zone/scripts/three_zone_example_data.py
- python /home/travis/miniconda/envs/asimtest/lib/python$TRAVIS_PYTHON_VERSION/site-packages/activitysim/examples/example_multiple_zone/scripts/two_zone_example_data.py
- python /home/travis/miniconda/envs/asimtest/lib/python$TRAVIS_PYTHON_VERSION/site-packages/activitysim/examples/example_multiple_zone/scripts/three_zone_example_data.py
# pycodestyle
- pycodestyle activitysim
# run specific TEST_SUITE job on travis to avoid job max time
- travis_wait 50 py.test $TEST_SUITE --cov activitysim --cov-report term-missing --durations=0
- coveralls
