language: python
python:
- '2.7'
install:
- sudo pip install conda
- sudo conda init
- |
  conda create -p $HOME/py --yes pip numpy pandas pytest "python=$TRAVIS_PYTHON_VERSION"
- export PATH=$HOME/py/bin:$PATH
- easy_install -U setuptools
- pip install pytest-cov coveralls pep8
- pip install .
script:
- pep8 activitysim
- py.test --cov activitysim --cov-report term-missing
after_success:
- coveralls
notifications:
  slack:
    secure: eD/LGUBVwbaFBsBALGmPVerRwF6/PRV3PoBpUYUmL7bKyBJZYwcFCb5t8thZvMF8lcHoF0e5xO7L8DoPuws2+mJCiSDH7QD3oGsLE9DoVMFKsIqvzv0oc6qrWf8LjPqcn3XBnXHOvmogRDaaeTCr8KuYEFtwqmwu3YW0/oWYPWk=
