
zone_system: 1

skims:
  taz: skims.omx


# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: False
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: False
#alternate dir to read/write skim cache (defaults to output_dir)
#cache_dir: data/cache

