# Some data values in the spec file will refer to missing values stored
# as NaN in the data.  This requires the `fastmath` setting to
# be set to `false` to avoid errors in the sharrow implementation.
compute_settings:
  fastmath: false

OUTBOUND_SPEC: school_escorting_outbound.csv
OUTBOUND_COEFFICIENTS: school_escorting_coefficients_outbound.csv

INBOUND_SPEC: school_escorting_inbound.csv
INBOUND_COEFFICIENTS: school_escorting_coefficients_inbound.csv

OUTBOUND_COND_SPEC: school_escorting_outbound_cond.csv
OUTBOUND_COND_COEFFICIENTS: school_escorting_coefficients_outbound_cond.csv

ALTS: school_escorting_alts.csv

LOGIT_TYPE: MNL

NUM_ESCORTEES: 3
NUM_CHAPERONES: 2

preprocessor_outbound:
  SPEC: school_escorting_preprocessor_outbound
  DF: df
  TABLES:
    - persons
    - tours

preprocessor_inbound:
  SPEC: school_escorting_preprocessor_inbound
  DF: df
  TABLES:
    - persons
    - tours

preprocessor_outbound_cond:
  SPEC: school_escorting_preprocessor_outbound
  DF: df
  TABLES:
    - persons
    - tours

SIMULATE_CHOOSER_COLUMNS:
  - home_zone_id
  - income
  - auto_ownership
  - num_workers

CONSTANTS:
  max_bin_difference_between_departure_times: 1
  mins_per_time_bin: 60
