
inherit_settings: True

# raise error if any sub-process fails without waiting for others to complete
fail_fast: True

## - ------------------------- production config
#multiprocess: True
#strict: False
#mem_tick: 0
#use_shadow_pricing: True
#
#
## - full sample - 2732722 households on 64 processor 432 GiB RAM
#households_sample_size:  0
#chunk_size:  80000000000
#num_processes: 60

# - full sample - 2732722 households on Standard_M128s
#households_sample_size:  0
#chunk_size:  0
#num_processes: 124


# - ------------------------- dev config
multiprocess: False
strict: False
mem_tick: 30
use_shadow_pricing: False

# - 10% sample
households_sample_size:  287519
hh_ids: 10_pct_hh_ids.csv

#households_sample_size:  100

chunk_size: 1500000000
num_processes: 3

# - tracing
#trace_hh_id: 324105
trace_od:
trace_hh_id: 324105
#trace_od: [5, 11]

# to resume after last successful checkpoint, specify resume_after: _
# resume_after: atwork_subtour_mode_choice

models:
  ### mp_initialize step
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  ### mp_households step
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  ### mp_summarize step
  - write_data_dictionary
  - write_tables

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_households
    begin: school_location
    #num_processes: 9
    #chunk_size: 1000000000
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary


output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
    - school_shadow_prices
    - raw_school_destination_size
    - school_destination_size
    - school_modeled_size
    - workplace_shadow_prices
    - raw_workplace_destination_size
    - workplace_destination_size
    - workplace_modeled_size

