# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: False
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: True

zone_system: 1
name: prototype_mtc

taz_skims:
    omx: skims.omx
    zarr: skims.zarr
    zarr-digital-encoding:
        - regex: ".*_BOARDS"
          joint_dict: joined_board
        - regex: ".*_FAR"
          joint_dict: joined_fare
        - regex: ".*_XWAIT"
          joint_dict: joined_xwait
        - regex: ".*_WAUX"
          joint_dict: joined_waux
        - regex: ".*_IWAIT"
          joint_dict: joined_iwait
        - regex: ".*_KEYIVT"
          joint_dict: joined_keyivt
        - regex: ".*_WAIT"
          joint_dict: joined_wait
        - regex: "DISTWALK|DISTBIKE"
          joint_dict: joined_walkbike

skim_time_periods:
    time_window: 1440
    period_minutes: 60
    periods: [0, 3, 5, 9, 14, 18, 24] # 3=3:00-3:59, 5=5:00-5:59, 9=9:00-9:59, 14=2:00-2:59, 18=6:00-6:59
    labels: ['EA', 'EA', 'AM', 'MD', 'PM', 'EV']
