
inherit_settings: True

write_raw_tables: False
rng_base_seed: 0

use_shadow_pricing: False

# number of households to simulate
households_sample_size:  0

# to resume after last successful checkpoint, specify resume_after: _
#resume_after: initialize_households

trace_hh_id: 2367040

# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    index_col: household_id
    column_map:
      HHID: household_id
    drop_columns:
      - SERIALNO
      - PUMA5
      - UNITTYPE
      - NOC
      - BLDGSZ
      - TENURE
      - hinccat1
      - hinccat2
      - hhagecat
      - hsizecat
      - hfamily
      - hunittype
      - hNOCcat
      - hwrkrcat
      - h0004
      - h0511
      - h1215
      - h1617
      - h1824
      - h2534
      - h3549
      - h5064
      - h6579
      - h80up
      - hwork_f
      - hwork_p
      - huniv
      - hnwork
      - hretire
      - hpresch
      - hschpred
      - hschdriv
      - htypdwel
      - hownrent
      - hadnwst
      - hadwpst
      - hadkids
      - bucketBin
      - originalPUMA
      - hmultiunit
      # artifact column in sample data write_raw_tables
      #- chunk_id
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    column_map:
      PERID: person_id
    drop_columns:
      - RELATE
      - ESR
      - GRADE
      - PAUG
      - DDP
      - WEEKS
      - HOURS
      - MSP
      - POVERTY
      - EARNS
      - pagecat
      - padkid
  - tablename: land_use
    filename: land_use.csv
    index_col: TAZ
    column_map:
      ZONE: TAZ
    drop_columns:
      - HHPOP
      - EMPRES
      - SFDU
      - MFDU
      - HHINCQ1
      - HHINCQ2
      - HHINCQ3
      - HHINCQ4
      - SHPOP62P
      - AGE0004
      - AGE2044
      - AGE4564
      - AGE65P
      - ZERO
      - hhlds
      - sftaz
      - gqpop


output_tables:
  h5_store: False
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants

models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
#  - stop_frequency
#  - trip_purpose
#  - trip_destination
#  - trip_purpose_and_destination
#  - trip_scheduling
#  - trip_mode_choice
  - write_data_dictionary
  - track_skim_usage
  - write_tables

