
inherit_settings: True

write_raw_tables: False
rng_base_seed: 0

use_shadow_pricing: False

# turn writing of sample_tables on and off for all models
want_dest_choice_sample_tables: False

# number of households to simulate
households_sample_size:  0

# to resume after last successful checkpoint, specify resume_after: _
#resume_after: initialize_households

trace_hh_id:


output_tables:
  h5_store: False
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips
    - joint_tour_participants

models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
#  - stop_frequency
#  - trip_purpose
#  - trip_destination
#  - trip_purpose_and_destination
#  - trip_scheduling
#  - trip_mode_choice
#  - write_data_dictionary
#  - track_skim_usage
#  - write_trip_matrices
  - write_tables

