################
# build the latest activitysim
################

FROM activitysim-dependencies AS activitysim-develop

WORKDIR /usr/node
COPY . ./

RUN pip install -e .

SHELL ["conda", "run", "-n", "ASIM-DEV", "/bin/bash", "-c"]
RUN echo "Make sure activitysim are installed:"
RUN python -c "import activitysim"
RUN python -c "import orca"