################
# build the latest activitysim
# also allow live debugging
################

FROM activitysim-dependencies AS activitysim-debug

WORKDIR /usr/node
COPY . ./

RUN pip install -e .

RUN pip install debugpy

SHELL ["conda", "run", "-n", "ASIM-DEV", "/bin/bash", "-c"]
RUN echo "Make sure activitysim are installed:"
RUN python -c "import activitysim"
RUN python -c "import orca"