#
annotate_tables:
  - tablename: persons
    annotate:
      SPEC: annotate_persons
      DF: persons
      TABLES:
        - households
  - tablename: households
    annotate:
      SPEC: annotate_households
      DF: households
      TABLES:
        - persons
