PROBS_SPEC: trip_purpose_probs.csv

preprocessor:
  SPEC: trip_purpose_annotate_trips_preprocessor
  DF: trips
  TABLES:
    - persons
    - tours

probs_join_cols:
  - primary_purpose
  - outbound
  - trip_num
  - multistop

use_depart_time: False