METADATA:
  CHOOSER: tours
  INPUT:
    persons:
    trips:
    tours:
  OUTPUT:
    trips:
      - start_period
      - end_period

SPECIFICATION: trip_scheduling_choice.csv
COEFFICIENTS: trip_scheduling_choice_coeff.csv

SAMPLE_ALTERNATIVES: trip_departure_sample_patterns.csv

PREPROCESSOR:
  SPEC: trip_scheduling_choice_preprocessor
  DF: tours
  TABLES:
    - persons
    - trips