inherit_settings: True

# - shadow pricing

MAX_SHADOW_PRICE_ITERATIONS: 10
MAX_SHADOW_PRICE_ITERATIONS_SAVED: 1

# model adds these tables (informational - not added if commented out)
SHADOW_PRICE_TABLE: school_shadow_prices
MODELED_SIZE_TABLE: school_modeled_size

# not loaded if commented out
#SAVED_SHADOW_PRICE_TABLE_NAME: school_shadow_prices.csv

# ignore criteria for zones smaller than size_threshold
SIZE_THRESHOLD: 100

# zone passes if modeled is within percent_tolerance of  predicted_size
PERCENT_TOLERANCE: 5

# max percentage of zones allowed to fail
FAIL_THRESHOLD: 10
