
inherit_settings: True

households_sample_size: 100
multiprocess: False
chunk_size: 3000000000

check_for_variability: False

#trace household id; comment out for no trace
# household with all tour categories
trace_hh_id: 1269102

# trace origin, destination in accessibility calculation
trace_od: [5, 11]

models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - _school_location_sample
  - _school_location_logsums
  - school_location_simulate
  - _workplace_location_sample
  - _workplace_location_logsums
  - workplace_location_simulate
  - auto_ownership_simulate
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - _joint_tour_destination_sample
  - _joint_tour_destination_logsums
  - joint_tour_destination_simulate
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - _atwork_subtour_destination_sample
  - _atwork_subtour_destination_logsums
  - atwork_subtour_destination_simulate
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  - write_data_dictionary
  - write_tables

#resume_after: school_location_simulate
#
#resume: _workplace_location_sample
#restore_checkpoint: school_location_simulate



# 160 GB
#chunk_size: 10000000000


multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_households
    begin: _school_location_sample
    num_processes: 3
    stagger: 10
    #chunk_size: 1000000000
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary

#multiprocess_steps:
#  - name: mp_initialize_landuse
#    begin: initialize_landuse
#  - name: mp_accessibility
#    begin: compute_accessibility
#    num_processes: 2
#    slice:
#      tables:
#        - accessibility
#      except:
#        - land_use
#  - name: mp_initialize_households
#    begin: initialize_households
#  - name: mp_households
#    begin: _school_location_sample
#    # num_processes = 0 means use all available cpus
#    num_processes: 2
#    slice:
#      tables:
#        - households
#        - persons
#  - name: mp_summarize
#    begin: write_data_dictionary


output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - trips
    - tours
