# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema

logging:
  version: 1
  disable_existing_loggers: true


  # Configuring the default (root) logger is highly recommended
  root:
    level: NOTSET
    handlers: [console, logfile]

  loggers:

    activitysim:
      level: INFO
      handlers: [console, logfile]
      propagate: false

    orca:
      level: WARN
      handlers: [console, logfile]
      propagate: false

    filelock:
      level: WARN

    sharrow:
      level: INFO

    blib2to3:
      level: WARN

    black:
      level: WARN

  handlers:

    logfile:
      class: logging.FileHandler
      filename: !!python/object/apply:activitysim.core.config.log_file_path ['activitysim.log']
      mode: w
      formatter: fileFormatter
      level: NOTSET

    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      level: !!python/object/apply:activitysim.core.mp_tasks.if_sub_task [WARNING, NOTSET]
      formatter: elapsedFormatter

  formatters:

    simpleFormatter:
      class: logging.Formatter
      format: '%(levelname)s - %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'

    fileFormatter:
      class: logging.Formatter
      format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'

    elapsedFormatter:
      (): activitysim.core.tracing.ElapsedTimeFormatter
      format: '[{elapsedTime}] {levelname:s}: {message:s}'
      style: '{'
