package:
  name: activitysim
  version: "0.1.1"

source:
  fn: activitysim-0.1.1.tar.gz
  url: https://pypi.python.org/packages/source/a/activitysim/activitysim-0.1.1.tar.gz
  md5: e91e5292f4610152ba5170264495a9f5
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - activitysim = activitysim:main
    #
    # Would create an entry point called activitysim that calls activitysim.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - cytoolz >=0.7
    - numpy >=1.8.0
    - openmatrix >=0.2.2
    - orca >=1.1
    - pandas >=0.13.1
    - pytables >=3.1.0
    - pyyaml >=3.0
    - toolz >=0.7
    - zbox >=1.2

  run:
    - python
    - cytoolz >=0.7
    - numpy >=1.8.0
    - openmatrix >=0.2.2
    - orca >=1.1
    - pandas >=0.13.1
    - pytables >=3.1.0
    - pyyaml >=3.0
    - toolz >=0.7
    - zbox >=1.2

test:
  # Python imports
  imports:
    - activitysim
    - activitysim.cdap
    - activitysim.defaults
    - activitysim.defaults.models
    - activitysim.defaults.models.util
    - activitysim.defaults.tables
    - activitysim.util
  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/synthicity/activitysim
  license: GNU Affero General Public License v3
  summary: 'Travel modeling'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
