# Config for logging
# ------------------
# See http://docs.python.org/2.7/library/logging.config.html#configuration-dictionary-schema

logging:
  version: 1
  disable_existing_loggers: true


  # Configuring the default (root) logger is highly recommended
  root:
    level: !!python/name:logging.DEBUG
    handlers: [console, logfile]

  loggers:

    activitysim:
      level: !!python/name:logging.DEBUG
      handlers: [console, logfile]
      propagate: false

    orca:
      level: !!python/name:logging.WARN
      handlers: [console, logfile]
      propagate: false

  handlers:

    logfile:
      class: logging.FileHandler
      filename: !!python/object/apply:activitysim.core.tracing.log_file_path ['asim.log']
      mode: w
      formatter: fileFormatter
      level: !!python/name:logging.NOTSET

    console:
      class: logging.StreamHandler
      stream: ext://sys.stdout
      formatter: simpleFormatter
      #level: !!python/name:logging.NOTSET
      level: !!python/name:logging.DEBUG

  formatters:

    simpleFormatter:
      class: !!python/name:logging.Formatter
      format: '%(levelname)s - %(name)s - %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'

    fileFormatter:
      class: !!python/name:logging.Formatter
      format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'

