inherit_settings: True


# household with mandatory, non mandatory, atwork_subtours, and joint tours
#trace_hh_id: 187746


# to resume after last successful checkpoint, specify resume_after: _
#resume_after: _

#cleanup_trace_files_on_resume: True

#trace_od: [5000, 11000]


output_tables:
  h5_store: False
  action: include
  prefix: final_
  sort: True
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips

