# input data store and skims
store: mtc_asim.h5
skims_file: skims.omx

# number of households to simulate
households_sample_size: 1000

# trace household id; comment out for no trace
trace_hh_id: 961042

# trace origin, destination in accessibility calculation
trace_od: [5, 11]

# internal settings
preload_3d_skims: True
chunk_size: 10000

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6

grade_school_max_age: 14

county_map:
    San Francisco: 1
    San Mateo: 2
    Santa Clara: 3
    Alameda: 4
    Contra Costa: 5
    Solano: 6
    Napa: 7
    Sonoma: 8
    Marin: 9

employment_map:
    1: full
    2: part
    3: not
    4: child

student_map:
    1: grade_or_high
    2: university
    3: not

person_type_map:
    1: full
    2: part
    3: university
    4: nonwork
    5: retired
    6: driving
    7: school
    8: preschool

household_type_map:
    0: null
    1: family_married
    2: family_male
    3: family_female
    4: nonfamily_male_alone
    5: nonfamily_male_notalone
    6: nonfamily_female_alone
    7: nonfamily_female_notalone

time_periods:
    hours:
        - 0
        - 11
        - 16
        - 24
    labels:
        - AM
        - MD
        - PM

