
inherit_settings: True

beam_skims_url: https://beam-outputs.s3.amazonaws.com/output/austin/austin-prod-200k-skims-with-h3-index-final__2020-04-18_09-44-24_wga/ITERS/it.0/0.skimsOD.UrbanSim.Full.csv.gz

create_skims_from_beam: True
usim_zone_geoms: h3
# usim_zone_shapefile:

create_inputs_from_usim_data: True
usim_data_store: model_data.h5


# raise error if any sub-process fails without waiting for others to complete
fail_fast: True

# - ------------------------- production config
#multiprocess: True
#strict: False
#mem_tick: 0
#use_shadow_pricing: True

# - full sample - 2875192 households on 64 processor 432 GiB RAM
#households_sample_size:  0
#chunk_size:  80000000000
#num_processes: 60
#stagger: 0

# - full sample - 2875192 households on Standard_M128s
#households_sample_size:  0
#chunk_size:  0
#num_processes: 124
#stagger: 0


# - ------------------------- dev config
multiprocess: True
strict: False
mem_tick: 0
use_shadow_pricing: False


## - small sample
#households_sample_size:  5000
#chunk_size: 500000000
#num_processes: 2
#stagger: 5


## - example sample
households_sample_size: 0
chunk_size: 5000000000
num_processes: 24
stagger: 0


# - tracing
trace_hh_id: 
trace_od:
# trace_hh_id: 195809
#trace_od: [5, 11]

# to resume after last successful checkpoint, specify resume_after: _
# resume_after: _

models:
  ### mp_initialize step
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  ### mp_households step
  - school_location
  - workplace_location
  # - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  ### mp_summarize step
  - generate_beam_plans
  - write_data_dictionary
  - write_tables

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_households
    begin: school_location
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: generate_beam_plans


output_tables:
  action: include
  prefix: final_
  tables:
    - land_use
    - households
    - persons
    - tours
    - trips
    - beam_plans