
inherit_settings: True

# - production config

multiprocess: True
mem_tick: 0
profile: False
strict: False

# Standard_E64s_v3
#households_sample_size:  0
#chunk_size:  90000000000
#num_processes: 60
#stagger: 5

# Standard_M128s
households_sample_size:  0
chunk_size:  0
num_processes: 120
stagger: 0


# - tracing
trace_hh_id:
trace_od:


models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - school_location
  - _workplace_location_sample
  - _workplace_location_logsums
  - workplace_location_simulate
  - auto_ownership_simulate
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - _joint_tour_destination_sample
  - _joint_tour_destination_logsums
  - joint_tour_destination_simulate
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - _atwork_subtour_destination_sample
  - _atwork_subtour_destination_logsums
  - atwork_subtour_destination_simulate
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  - write_data_dictionary
  - write_tables

multiprocess_steps:
  - name: mp_initialize
    begin: initialize_landuse
  - name: mp_households
    begin: school_location
    slice:
      tables:
        - households
        - persons
  - name: mp_summarize
    begin: write_data_dictionary

output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints

