#input data store and skims
#input_store: NetworkData.h5

input_table_list:
  - tablename: TAZ
    filename: taz.csv
    index_col: TAZ
  - tablename: MAZ
    filename: maz.csv
    index_col: MAZ
  - tablename: TAP
    filename: tap.csv
    index_col: TAP
  - tablename: MAZtoMAZ
    filename: maz2maz.csv
  - tablename: MAZtoTAP
    filename: maz2tap.csv

network_los:

  zone_system: 1

  skims:
    taz: taz_skims.omx

    tap:
      - tap_skims_locl.omx
      - tap_skims_prem.omx


#number of households to simulate
households_sample_size: 1000

skim_time_periods:
    period_minutes: 60
    periods:
        - 0
        - 11
        - 16
        - 24
    labels:
        - AM
        - MD
        - PM


