SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - home_zone_id
  - household_id
  - is_low_income
  - is_very_high_income
  - is_fulltime_worker
  - areatype
  - auto_ownership
  - num_workers
  
SAMPLE_SPEC: workplace_location_sample.csv
SPEC: workplace_location.csv
COEFFICIENTS: workplace_location_coeffs.csv

LOGSUM_SETTINGS: tour_mode_choice.yaml
LOGSUM_PREPROCESSOR: nontour_preprocessor
LOGSUM_TOUR_PURPOSE: work

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 34
OUT_PERIOD: 16

DEST_CHOICE_COLUMN_NAME: workplace_zone_id

annotate_persons:
  SPEC: annotate_persons_workplace
  DF: persons
  TABLES:
    - land_use

annotate_households:
  SPEC: annotate_households_workplace
  DF: households
  TABLES:
    - persons

# - shadow pricing


# income_segment is in households, but we want to count persons
CHOOSER_TABLE_NAME: persons

# size_terms model_selector
MODEL_SELECTOR: workplace

# we can't use use household income_segment as this will also be set for non-workers
CHOOSER_SEGMENT_COLUMN_NAME: work_segment

# boolean column to filter choosers (True means keep)
CHOOSER_FILTER_COLUMN_NAME: is_worker

# FIXME - these are assigned to persons in annotate_persons. we need a better way to manage this
SEGMENT_IDS:
  white_collar: 1
  service: 2
  health: 3
  retail_food: 4
  blue_collar: 5

# model adds these tables (informational - not added if commented out)
SHADOW_PRICE_TABLE: workplace_shadow_prices
MODELED_SIZE_TABLE: workplace_modeled_size

# not loaded if commented out
SAVED_SHADOW_PRICE_TABLE_NAME: workplace_shadow_prices.csv


