inherit_settings: True

# input tables
input_table_list:
  - tablename: households
    filename: households.csv
    index_col: household_id
    rename_columns:
      HHID: household_id
      PERSONS: hhsize
      workers: num_workers
      VEHICL: auto_ownership
      MAZ: home_zone_id
    keep_columns:
      - home_zone_id
      - income
      - hhsize
      - HHT
      - auto_ownership
      - num_workers
  - tablename: persons
    filename: persons.csv
    index_col: person_id
    rename_columns:
      PERID: person_id
    keep_columns:
      - household_id
      - age
      - PNUM
      - sex
      - pemploy
      - pstudent
      - ptype
  - tablename: land_use
    filename: land_use.csv
    index_col: zone_id
    rename_columns:
      MAZ: zone_id
      COUNTY: county_id
    keep_columns:
      - TAZ
      - DISTRICT
      - SD
      - county_id
      - TOTHH
      - TOTPOP
      - TOTACRE
      - RESACRE
      - CIACRE
      - TOTEMP
      - AGE0519
      - RETEMPN
      - FPSEMPN
      - HEREMPN
      - OTHEMPN
      - AGREMPN
      - MWTEMPN
      - PRKCST
      - OPRKCST
      - area_type
      - HSENROLL
      - COLLFTE
      - COLLPTE
      - TOPOLOGY
      - TERMINAL
      - access_dist_transit

network_los:

  zone_system: 2

  skims:
    taz: taz_skims.omx

  tables:
    maz_to_maz:
      - maz_to_maz_walk.csv
      - maz_to_maz_bike.csv
    maz_to_taz: maz_to_taz.csv

skim_time_periods:
    period_minutes: 60
    periods:
        - 0
        - 6
        - 11
        - 16
        - 20
        - 24
    labels:
        - EA
        - AM
        - MD
        - PM
        - EV


#resume_after: initialize_landuse
