SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - person_id
  - income_segment
  - workplace_taz

LOGSUM_SETTINGS: tour_mode_choice.yaml

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: workplace_taz
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 14
OUT_PERIOD: 14
