SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - person_id
  - income_segment
  - workplace_taz

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: workplace_taz
ALT_DEST_COL_NAME: dest_TAZ
IN_PERIOD: 12
OUT_PERIOD: 12

