SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - tour_type
  - TAZ
  - household_id

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: TAZ
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 12
OUT_PERIOD: 12
