
CHOOSER_COLUMNS:
  - ptype
  - hhsize
  - roundtrip_auto_time_to_work
  - num_workers
  - income_in_thousands
  - work_and_school_and_worker
  - work_and_school_and_student
  - workplace_in_cbd
  - home_is_rural
  - mandatory_tour_frequency
  - is_worker
  - is_student
