SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - TAZ
  - is_university
  - is_highschool
  - is_gradeschool


# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: TAZ
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 8
OUT_PERIOD: 17


annotate_persons:
  SPEC: annotate_persons_school
  DF: persons
