#input data store and skims
input_store: mtc_asim.h5
skims_file: skims.omx

#number of households to simulate
households_sample_size:  100
# simulate all households
#households_sample_size: 0

chunk_size: 0

# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# - shadow pricing global switches

# turn shadow_pricing on and off for all models (e.g. school and work)
# shadow pricing is deprecated for less than full samples
# see shadow_pricing.yaml for additional settings
use_shadow_pricing: False


# - tracing

#trace household id; comment out or leave empty for no trace
# households with all tour types
#  [ 728370 1234067 1402924 1594625 1595333 1747572 1896849 1931818 2222690 2344951 2677154]
trace_hh_id: 701664

# trace origin, destination in accessibility calculation; comment out or leave empty for no trace
#trace_od: [5, 11]
trace_od:


models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - free_parking
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  - write_data_dictionary
  - track_skim_usage
  - write_tables

# to resume after last successful checkpoint, specify resume_after: _
#resume_after: trip_mode_choice

output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
    - accessibility
    - land_use
    - households
    - persons
    - tours
    - trips

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6

#upperEA	Upper limit on time of day for the Early morning time period		5
#upperAM	Upper limit on time of day for the AM peak time period		10
#upperMD	Upper limit on time of day for the Midday time period		15
#upperPM	Upper limit on time of day for the PM time peak period		19

skim_time_periods:
    hours:
        - 0
        - 6
        - 11
        - 16
        - 20
        - 24
    labels:
        - EA
        - AM
        - MD
        - PM
        - EV

# - value of time

# value_of_time = lognormal(np.log(median_value_of_time * mu), sigma).clip(min_vot, max_vot)

min_value_of_time: 1
max_value_of_time: 50
distributed_vot_mu: 0.684
distributed_vot_sigma: 0.85

household_median_value_of_time:
  1: 6.01
  2: 8.81
  3: 10.44
  4: 12.86
