store: mtc_asim.h5

households_sample_size: 1000

county_map:
    San Francisco: 1
    San Mateo: 2
    Santa Clara: 3
    Alameda: 4
    Contra Costa: 5
    Solano: 6
    Napa: 7
    Sonoma: 8
    Marin: 9

employment_map:
    1: "full"
    2: "part"
    3: "not"
    4: "child"

student_map:
    1: "high"
    2: "college"
    3: "not"
