#input data store and skims
store: mtc_asim.h5
skims_file: skims.omx

#number of households to simulate
households_sample_size: 100

#trace household id; comment out for no trace
#trace_hh_id: 961042

# trace origin, destination in accessibility calculation
#trace_od: [5, 11]

#internal settings 
chunk_size: 1000000


# comment out or set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

models:
  - initialize
  - compute_accessibility
  - school_location_sample
  - school_location_logsums
  - school_location_simulate
  - workplace_location_sample
  - workplace_location_logsums
  - workplace_location_simulate
  - auto_ownership_simulate
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination_choice
  - non_mandatory_tour_scheduling
  - annotate_table.model_name=annotate_tours
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination_sample
  - atwork_subtour_destination_logsums
  - atwork_subtour_destination_simulate
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice_simulate
  - create_simple_trips
  - trip_mode_choice_simulate
  - write_data_dictionary

#resume_after: tour_mode_choice_simulate

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6

grade_school_max_age: 14

county_map:
    San Francisco: 1
    San Mateo: 2
    Santa Clara: 3
    Alameda: 4
    Contra Costa: 5
    Solano: 6
    Napa: 7
    Sonoma: 8
    Marin: 9

employment_map:
    1: full
    2: part
    3: not
    4: child

student_map:
    1: grade_or_high
    2: university
    3: not

person_type_map:
    1: full          # FT_worker_age_16plus,
    2: part          # PT_worker_nonstudent_age_16plus,
    3: university    # University_student,
    4: nonwork       # Nonworker_nonstudent_age_16_64,
    5: retired       # Nonworker_nonstudent_age_65plus,
    6: driving       # Student_age_16_19_not_FT_wrkr_or_univ_stud,
    7: school        # Student_age_6_15_schpred,
    8: preschool     # Preschool_under_age_6


household_type_map:
    0: null
    1: family_married
    2: family_male
    3: family_female
    4: nonfamily_male_alone
    5: nonfamily_male_notalone
    6: nonfamily_female_alone
    7: nonfamily_female_notalone

skim_time_periods:
    hours:
        - 0
        - 11
        - 16
        - 24
    labels:
        - AM
        - MD
        - PM
