#input data store and skims
input_store: mtc_asim.h5
skims_file: skims.omx

#number of households to simulate
households_sample_size:  100
# simulate all households
#households_sample_size: 0

#trace household id; comment out or leave empty for no trace
#trace_hh_id: 1482966
trace_hh_id:

# trace origin, destination in accessibility calculation; comment out or leave empty for no trace
#trace_od: [5, 11]
trace_od:

chunk_size: 0

# set false to disable variability check in simple_simulate and interaction_simulate
check_for_variability: False

# set false to disable shadow_pricing
use_shadow_pricing: False

models:
  - initialize_landuse
  - compute_accessibility
  - initialize_households
  - school_location
  - workplace_location
  - auto_ownership_simulate
  - cdap_simulate
  - mandatory_tour_frequency
  - mandatory_tour_scheduling
  - joint_tour_frequency
  - joint_tour_composition
  - joint_tour_participation
  - joint_tour_destination_sample
  - joint_tour_destination_logsums
  - joint_tour_destination_simulate
  - joint_tour_scheduling
  - non_mandatory_tour_frequency
  - non_mandatory_tour_destination
  - non_mandatory_tour_scheduling
  - tour_mode_choice_simulate
  - atwork_subtour_frequency
  - atwork_subtour_destination_sample
  - atwork_subtour_destination_logsums
  - atwork_subtour_destination_simulate
  - atwork_subtour_scheduling
  - atwork_subtour_mode_choice
  - stop_frequency
  - trip_purpose
  - trip_destination
  - trip_purpose_and_destination
  - trip_scheduling
  - trip_mode_choice
  - write_data_dictionary
  - track_skim_usage
  - write_tables

# to resume after last successful checkpoint, specify resume_after: _
#resume_after: trip_mode_choice

output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
#    - accessibility
#    - land_use
#    - households
#    - persons
#    - trips
#    - tours

# area_types less than this are considered urban
urban_threshold: 4
cbd_threshold: 2
rural_threshold: 6

grade_school_max_age: 14

county_map:
    San Francisco: 1
    San Mateo: 2
    Santa Clara: 3
    Alameda: 4
    Contra Costa: 5
    Solano: 6
    Napa: 7
    Sonoma: 8
    Marin: 9

skim_time_periods:
    hours:
        - 0
        - 11
        - 16
        - 24
    labels:
        - AM
        - MD
        - PM

shadow_pricing_models:
  school: school_location
  work: workplace_location

