LOGIT_TYPE: NL
#LOGIT_TYPE: MNL

NESTS:
  name: root
  coefficient: 1.00
  alternatives:
      - name: AUTO
        coefficient: 0.72
        alternatives:
            - name: DRIVEALONE
              coefficient: 0.35
              alternatives:
                - DRIVEALONEFREE
                - DRIVEALONEPAY
            - name: SHAREDRIDE2
              coefficient: 0.35
              alternatives:
                - SHARED2FREE
                - SHARED2PAY
            - name: SHAREDRIDE3
              coefficient: 0.35
              alternatives:
                - SHARED3FREE
                - SHARED3PAY
      - name: NONMOTORIZED
        coefficient: 0.72
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  0.72
        alternatives:
            - name: WALKACCESS
              coefficient: 0.5
              alternatives:
              - WALK_LOC
              - WALK_LRF
              - WALK_EXP
              - WALK_HVY
              - WALK_COM
            - name: DRIVEACCESS
              coefficient: 0.5
              alternatives:
              - DRIVE_LOC
              - DRIVE_LRF
              - DRIVE_EXP
              - DRIVE_HVY
              - DRIVE_COM


VARIABLE_TEMPLATES:

CONSTANTS:
    valueOfTime: 8.00
    costPerMile: 18.48
    costShareSr2: 1.75
    costShareSr3: 2.50
    waitThresh: 10.00
    walkThresh: 1.0
    shortWalk: 0.333
    longWalk: 0.667
    walkSpeed: 3.00
    bikeThresh: 6.00
    bikeSpeed: 12.00
    maxCbdAreaTypeThresh: 2
    indivTour: 1.00000
    upperEA: 5
    upperAM: 10
    upperMD: 15
    upperPM: 19
