SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - income_segment
  - TAZ

LOGSUM_SETTINGS: tour_mode_choice.yaml
LOGSUM_PREPROCESSOR: nontour_preprocessor

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: TAZ
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 8
OUT_PERIOD: 17


annotate_persons:
  SPEC: annotate_persons_workplace
  DF: persons
  TABLES:
    - land_use
