## ActivitySim
## See full license in LICENSE.txt.


#HHT_NONE: 0
#HHT_FAMILY_MARRIED: 1
#HHT_FAMILY_MALE: 2
#HHT_FAMILY_FEMALE: 3
#HHT_NONFAMILY_MALE_ALONE: 4
#HHT_NONFAMILY_MALE_NOTALONE: 5
#HHT_NONFAMILY_FEMALE_ALONE: 6
#HHT_NONFAMILY_FEMALE_NOTALONE: 7

# convenience for expression files
HHT_NONFAMILY: [4, 5, 6, 7]
HHT_FAMILY: [1, 2, 3]

PSTUDENT_GRADE_OR_HIGH: 1
PSTUDENT_UNIVERSITY: 2
PSTUDENT_NOT: 3

GRADE_SCHOOL_MAX_AGE: 14
GRADE_SCHOOL_MIN_AGE: 5

SCHOOL_SEGMENT_NONE: 0
SCHOOL_SEGMENT_GRADE: 1
SCHOOL_SEGMENT_HIGH: 2
SCHOOL_SEGMENT_UNIV: 3

INCOME_SEGMENT_LOW: 1
INCOME_SEGMENT_MED: 2
INCOME_SEGMENT_HIGH: 3
INCOME_SEGMENT_VERYHIGH: 4

PEMPLOY_FULL: 1
PEMPLOY_PART: 2
PEMPLOY_NOT: 3
PEMPLOY_CHILD: 4

PTYPE_FULL: &ptype_full 1
PTYPE_PART: &ptype_part 2
PTYPE_UNIVERSITY: &ptype_university 3
PTYPE_NONWORK: &ptype_nonwork 4
PTYPE_RETIRED: &ptype_retired 5
PTYPE_DRIVING: &ptype_driving 6
PTYPE_SCHOOL: &ptype_school 7
PTYPE_PRESCHOOL:  &ptype_preschool 8

# these appear as column headers in non_mandatory_tour_frequency.csv
PTYPE_NAME:
  *ptype_full: PTYPE_FULL
  *ptype_part: PTYPE_PART
  *ptype_university: PTYPE_UNIVERSITY
  *ptype_nonwork: PTYPE_NONWORK
  *ptype_retired: PTYPE_RETIRED
  *ptype_driving: PTYPE_DRIVING
  *ptype_school: PTYPE_SCHOOL
  *ptype_preschool: PTYPE_PRESCHOOL


CDAP_ACTIVITY_MANDATORY: M
CDAP_ACTIVITY_NONMANDATORY: N
CDAP_ACTIVITY_HOME: H
