LOGIT_TYPE: MNL

preprocessor:
  SPEC: stop_frequency_annotate_tours_preprocessor
  DF: tours_merged
  TABLES:
    - persons
    - land_use
    - accessibility


CONSTANTS:
  TRANSIT_MODES:
    - WALK_LOC
    - WALK_LRF
    - WALK_EXP
    - WALK_HVY
    - WALK_COM
    - DRIVE_LOC
    - DRIVE_LRF
    - DRIVE_EXP
    - DRIVE_HVY
    - DRIVE_COM
  DRIVE_TO_TRANSIT_MODES:
    - DRIVE_LOC
    - DRIVE_LRF
    - DRIVE_EXP
    - DRIVE_HVY
    - DRIVE_COM
  NONMOTORIZED_MODES:
    - WALK
    - BIKE
  SHOP_TOUR: shopping
  MAINT_TOUR: othmaint
  SCHOOL_TOUR: school
  EATOUT_TOUR: eatout
  SOCIAL_TOUR: social
  num_atwork_subtours_map:
    no_subtours: 0
    eat: 1
    business1: 1
    maint: 1
    business2: 2
    eat_business: 2
