LOGIT_TYPE: MNL

preprocessor:
  SPEC: stop_frequency_annotate_tours_preprocessor
  DF: tours_merged
  TABLES:
    - persons
    - land_use
    - accessibility

SEGMENT_COL: primary_purpose

SPEC_SEGMENTS:
  - primary_purpose: work
    SPEC: stop_frequency_work.csv
    COEFFICIENTS: stop_frequency_coefficients_work.csv
  - primary_purpose: school
    SPEC: stop_frequency_school.csv
    COEFFICIENTS: stop_frequency_coefficients_school.csv
  - primary_purpose: univ
    SPEC: stop_frequency_univ.csv
    COEFFICIENTS: stop_frequency_coefficients_univ.csv
  - primary_purpose: social
    SPEC: stop_frequency_social.csv
    COEFFICIENTS: stop_frequency_coefficients_social.csv
  - primary_purpose: shopping
    SPEC: stop_frequency_shopping.csv
    COEFFICIENTS: stop_frequency_coefficients_shopping.csv
  - primary_purpose: eatout
    SPEC: stop_frequency_eatout.csv
    COEFFICIENTS: stop_frequency_coefficients_eatout.csv
  - primary_purpose: escort
    SPEC: stop_frequency_escort.csv
    COEFFICIENTS: stop_frequency_coefficients_escort.csv
  - primary_purpose: othmaint
    SPEC: stop_frequency_othmaint.csv
    COEFFICIENTS: stop_frequency_coefficients_othmaint.csv
  - primary_purpose: othdiscr
    SPEC: stop_frequency_othdiscr.csv
    COEFFICIENTS: stop_frequency_coefficients_othdiscr.csv
  - primary_purpose: atwork
    SPEC: stop_frequency_atwork.csv
    COEFFICIENTS: stop_frequency_coefficients_atwork.csv

CONSTANTS:
  TRANSIT_MODES:
    - WALK_LOC
    - WALK_LRF
    - WALK_EXP
    - WALK_HVY
    - WALK_COM
    - DRIVE_LOC
    - DRIVE_LRF
    - DRIVE_EXP
    - DRIVE_HVY
    - DRIVE_COM
  DRIVE_TO_TRANSIT_MODES:
    - DRIVE_LOC
    - DRIVE_LRF
    - DRIVE_EXP
    - DRIVE_HVY
    - DRIVE_COM
  NONMOTORIZED_MODES:
    - WALK
    - BIKE
  SHOP_TOUR: shopping
  MAINT_TOUR: othmaint
  SCHOOL_TOUR: school
  EATOUT_TOUR: eatout
  SOCIAL_TOUR: social
  num_atwork_subtours_map:
    no_subtours: 0
    eat: 1
    business1: 1
    maint: 1
    business2: 2
    eat_business: 2
