SAMPLE_SIZE: 30

SIMULATE_CHOOSER_COLUMNS:
  - home_zone_id
  - household_id
  - is_low_income
  - is_very_high_income
  - areatype

# model-specific logsum-related settings
CHOOSER_ORIG_COL_NAME: home_zone_id
ALT_DEST_COL_NAME: alt_dest
IN_PERIOD: 28
OUT_PERIOD: 16

DEST_CHOICE_COLUMN_NAME: school_zone_id

SAMPLE_SPEC: school_location_sample.csv
SPEC: school_location.csv
COEFFICIENTS: school_location_coeffs.csv

LOGSUM_SETTINGS: tour_mode_choice.yaml
LOGSUM_PREPROCESSOR: nontour_preprocessor

LOGSUM_TOUR_PURPOSE:
  k12_predrive: school
  k12_drive: school
  univ: univ

annotate_persons:
  SPEC: annotate_persons_school
  DF: persons

# - shadow pricing

# required by initialize_households when creating school_destination_size table
CHOOSER_TABLE_NAME: persons

# size_terms model_selector
MODEL_SELECTOR: school

# chooser column with segment_id for this segment type
CHOOSER_SEGMENT_COLUMN_NAME: school_segment

# boolean column to filter choosers (True means keep)
CHOOSER_FILTER_COLUMN_NAME: is_student

# FIXME - these are assigned to persons in annotate_persons. we need a better way to manage this
SEGMENT_IDS:
  k12_predrive: 1
  k12_drive : 2
  univ: 3


# model adds these tables (informational - not added if commented out)
SHADOW_PRICE_TABLE: school_shadow_prices
MODELED_SIZE_TABLE: school_modeled_size

# not loaded if commented out
SAVED_SHADOW_PRICE_TABLE_NAME: school_shadow_prices.csv
