
# list model_selectors and model_names of models that use shadow pricing
# This list identifies which size_terms to preload (which must be done in single process mode
# so predicted_size tables can be scaled to population)
# (and allows models to be renamed without changing model_selectors)
shadow_pricing_models:
  school: school_location
  workplace: workplace_location

# global switch to enable/disable loading of saved shadow prices
# (ignored if global use_shadow_pricing switch is False)
LOAD_SAVED_SHADOW_PRICES: True

MAX_ITERATIONS: 5
MAX_ITERATIONS_SAVED: 1

# ignore criteria for zones smaller than size_threshold
SIZE_THRESHOLD: 10

# zone passes if modeled is within percent_tolerance of  predicted_size
PERCENT_TOLERANCE: 5

# max percentage of zones allowed to fail
FAIL_THRESHOLD: 10

# CTRAMP or daysim
SHADOW_PRICE_METHOD: ctramp
#SHADOW_PRICE_METHOD: daysim

# ctramp-style shadow_pricing_method parameters
DAMPING_FACTOR: 0.7

# daysim-style shadow_pricing_method parameters
# FIXME should these be the same as PERCENT_TOLERANCE and FAIL_THRESHOLD above?
DAYSIM_ABSOLUTE_TOLERANCE: 50
DAYSIM_PERCENT_TOLERANCE: 10
