inherit_settings: True

skim_dict_factory: NumpyArraySkimFactory
#skim_dict_factory: MemMapSkimFactory

# read cached skims (using numpy memmap) from output directory (memmap is faster than omx )
read_skim_cache: True
# write memmapped cached skims to output directory after reading from omx, for use in subsequent runs
write_skim_cache: True

# rebuild and overwrite existing tap_tap_utilities cache
rebuild_tvpb_cache: True

taz_skims: taz_skims*.omx

# we require that skims for all tap_tap sets have unique names
# and can therefor share a single skim_dict without name collision
# e.g. TRN_XWAIT_FAST__AM, TRN_XWAIT_SHORT__AM, TRN_XWAIT_CHEAP__AM
tap_skims: tap_skims.omx


tap_lines: tap_lines.csv

maz_to_tap:
  walk:
    table: maz_to_tap_walk.csv
    # if provided, this column will be used (together with tap_lines table) to trim the near tap set
    # to only include the nearest tap to origin when more than oFne tap serves the same line
    tap_line_distance_col: DISTWALK
    max_dist: 1.2
  drive:
    table: maz_to_tap_drive.csv
    # although maz_tap utility calculations use both DIST and drive_time,
    # it looks like drive_time is a linear function of DIST so we can use either column to trim to nearest
    tap_line_distance_col: DIST
