inherit_settings: True

network_los:

  zone_system: 1

  skims:
    taz: skims.omx



skim_time_periods:
    period_minutes: 60
    periods:
        - 0
        - 6
        - 11
        - 16
        - 20
        - 24
    labels:
        - EA
        - AM
        - MD
        - PM
        - EV
