
SPEC: atwork_subtour_frequency.csv
COEFFICIENTS: atwork_subtour_frequency_coefficients.csv

preprocessor:
  SPEC: atwork_subtour_frequency_annotate_tours_preprocessor
  DF: df
  TABLES:
    - land_use
    - tours
    - joint_tour_participants
