annotate_persons:
  SPEC: annotate_persons_nmtf
  DF: persons
  TABLES:
    - tours

preprocessor:
  SPEC: non_mandatory_tour_frequency_annotate_persons_preprocessor
  DF: persons
  TABLES:
    - tours
#    - accessibility
