LOGIT_TYPE: NL
#LOGIT_TYPE: MNL

NESTS:
  name: root
  coefficient: 1.00
  alternatives:
      - name: AUTO
        coefficient: 0.72
        alternatives:
            - name: DRIVEALONE
              coefficient: 0.35
              alternatives:
                - DRIVEALONEFREE
                - DRIVEALONEPAY
            - name: SHAREDRIDE2
              coefficient: 0.35
              alternatives:
                - SHARED2FREE
                - SHARED2PAY
            - name: SHAREDRIDE3
              coefficient: 0.35
              alternatives:
                - SHARED3FREE
                - SHARED3PAY
      - name: NONMOTORIZED
        coefficient: 0.72
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  0.72
        alternatives:
            - name: WALKACCESS
              coefficient: 0.5
              alternatives:
              - WALK_LOC
              - WALK_LRF
              - WALK_EXP
              - WALK_HVY
              - WALK_COM
            - name: DRIVEACCESS
              coefficient: 0.5
              alternatives:
              - DRIVE_LOC
              - DRIVE_LRF
              - DRIVE_EXP
              - DRIVE_HVY
              - DRIVE_COM
      - name: RIDEHAIL
        coefficient: 0.36
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED

SPEC: tour_mode_choice.csv
COEFFS: tour_mode_choice_coeffs.csv

CONSTANTS:
    #valueOfTime: 8.00
    costPerMile: 18.29
    costShareSr2: 1.75
    costShareSr3: 2.50
    waitThresh: 10.00
    walkThresh: 1.50
    shortWalk: 0.333
    longWalk: 0.667
    walkSpeed: 3.00
    bikeThresh: 6.00
    bikeSpeed: 12.00
    maxCbdAreaTypeThresh: 2
    indivTour: 1.00000
    upperEA: 5
    upperAM: 10
    upperMD: 15
    upperPM: 19
    # RIDEHAIL Settings
    Taxi_baseFare: 2.20
    Taxi_costPerMile: 2.30
    Taxi_costPerMinute: 0.10
    Taxi_waitTime_mean:
      1: 5.5
      2: 9.5
      3: 13.3
      4: 17.3
      5: 26.5
    Taxi_waitTime_sd: 
      1: 0
      2: 0
      3: 0
      4: 0
      5: 0
    TNC_single_baseFare: 2.20
    TNC_single_costPerMile: 1.33
    TNC_single_costPerMinute: 0.24
    TNC_single_costMinimum: 7.20
    TNC_single_waitTime_mean: 
      1: 4.7
      2: 6.3
      3: 8.4
      4: 8.5
      5: 10.3
    TNC_single_waitTime_sd: 
      1: 0
      2: 0
      3: 0
      4: 0
      5: 0
    TNC_shared_baseFare: 2.20
    TNC_shared_costPerMile: 0.64
    TNC_shared_costPerMinute: 0.10
    TNC_shared_costMinimum: 3.00
    TNC_shared_IVTFactor: 1.5
    TNC_shared_waitTime_mean: 
      1: 7.0
      2: 8.0
      3: 11.0
      4: 15.0
      5: 15.0
    TNC_shared_waitTime_sd: 
      1: 0
      2: 0
      3: 0
      4: 0
      5: 0
    min_waitTime: 0
    max_waitTime: 50

# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use
    - tours

nontour_preprocessor:
  SPEC: tour_mode_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use

# to reduce memory needs filter chooser table to these fields
LOGSUM_CHOOSER_COLUMNS:
  - tour_type
  - hhsize
  - density_index
  - age
  - age_16_p
  - age_16_to_19
  - auto_ownership
  - number_of_participants
  - tour_category
  - num_workers
  - value_of_time
  - free_parking_at_work


MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
