# vehicle_choice.yaml

SPEC: vehicle_type_choice_op4.csv
COEFFICIENTS: vehicle_type_choice_op4_coefficients.csv
ALTS: vehicle_type_choice_op4_alternatives.csv

# SPEC: vehicle_type_choice_op2.csv
# COEFFICIENTS: vehicle_type_choice_op2_coefficients.csv
# ALTS: vehicle_type_choice_op2_alternatives.csv

# comment out this line or delete the file name to toggle
# on/off the probabilistic second stage
# PROBS_SPEC: vehicle_type_choice_op2_fuel_type_probs.csv

LOGIT_TYPE: MNL
CHOICE_COL: vehicle_type

# additional vehicle_type_data for use in expressions
VEHICLE_TYPE_DATA_FILE: vehicle_type_data.csv
# creates a dataframe accessible as vehicle_type_data and is joined to the combinatorial_alts if available
# age is computed as (1 + SCENARIO_YEAR - VEHICLE_YEAR_COL)
# entries in this data should match what is specified in the combinatorial_alts
BODY_TYPE_COL: body_type
FUEL_TYPE_COL: fuel_type
VEHICLE_YEAR_COL: vehicle_year
SCENARIO_YEAR: 2017

combinatorial_alts:
  body_type:
    - Car
    - Van
    - SUV
    - Pickup
    - Motorcycle
  age:
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
  fuel_type:
    - Gas
    - Diesel
    - Hybrid
    - PEV
    - BEV

preprocessor:
  SPEC: vehicle_type_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use
    - vehicles
    - persons
    - households

annotate_persons:
  SPEC: annotate_persons_vehicle_type
  DF: persons
  TABLES:
    - vehicles

annotate_households:
  SPEC: annotate_households_vehicle_type
  DF: households
  TABLES:
    - persons
    - vehicles

MODE_CHOICE_LOGSUM_COLUMN_NAME: vehicle_choice_logsum

CONSTANTS:
  # Select region for model and input the MSA population
  # Expressions for CBSA values are implemented for:
  #   San Francisco (SFO), San Diego (SAN), Atlanta (ATL),
  #   Seattle (SEA), Detroit (DET), Minneapolis (MSP),
  #   Washington DC (DCA), Oregon (OREG), Ohio (OHIO)
  CBSA: SFO
  MSA_POP: 3320000
