# vehicle_choice.yaml

# last entry in spec needs to be a non-hh-veh option
SPEC: vehicle_allocation.csv
COEFFICIENTS: vehicle_allocation_coefficients.csv

LOGIT_TYPE: MNL

# additional vehicle_type_data for use in expressions
VEHICLE_TYPE_DATA_FILE: vehicle_type_data.csv
# creates a dataframe accessible as vehicle_type_data and is joined to the combinatorial_alts if available
# age is computed as (1 + SCENARIO_YEAR - VEHICLE_YEAR_COL)
SCENARIO_YEAR: 2017
# columns to include in the chooser table from the vehicle type data
# columns will be joined for each alternative with the alt number added.
# e.g. Range will be added as Range_1 for veh_num1, Range_2 for veh_num2, etc.
VEHICLE_DATA_TO_INCLUDE:
 - Range
 - NewPrice

preprocessor:
  SPEC: vehicle_allocation_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use
    - vehicles
    - persons
    - households

# annotate_tours:
#   SPEC: annotate_tours_vehicle_allocation
#   DF: tours
#   TABLES:
#     - vehicles

# will create columns in the tour table selecting a vehicle for each of the following
# occupancy levels. They are named vehicle_occup_1, vehicle_occup_2, ...
# if not supplied, will default to only one occupancy level of 1
OCCUPANCY_LEVELS:
  - 1
  - 2
  - 3.5
