# vehicle_choice.yaml

SPEC: vehicle_choice_op4.csv
COEFFICIENTS: vehicle_choice_op4_coefficients.csv
PROBS_SPEC: vehicle_choice_fuel_type_probs.csv

LOGIT_TYPE: MNL

preprocessor:
  SPEC: vehicle_choice_annotate_choosers_preprocessor
  DF: choosers
  TABLES:
    - land_use
    - vehicles
    - persons
    - households

annotate_persons:
  SPEC: annotate_persons_vehicle_type
  DF: persons
  TABLES:
    - vehicles

annotate_households:
  SPEC: annotate_households_vehicle_type
  DF: households
  TABLES:
    - persons
    - vehicles

MODE_CHOICE_LOGSUM_COLUMN_NAME: vehicle_choice_logsum
