LOGIT_TYPE: MNL

SPEC: joint_tour_frequency.csv
COEFFICIENTS: joint_tour_frequency_coeffs.csv

preprocessor:
  SPEC: joint_tour_frequency_annotate_households_preprocessor
  DF: households
  TABLES:
    #- persons
    - accessibility
