SPEC: trip_mode_choice.csv
#COEFFICIENTS: trip_mode_choice_coeffs.csv
LEGACY_COEFFICIENTS: trip_mode_choice_coeffs.csv

LOGIT_TYPE: NL

NESTS:
  name: root
  coefficient: 1.00
  alternatives:
      - name: AUTO
        coefficient: 0.72
        alternatives:
            - DRIVEALONE
            - SHARED2
            - SHARED3
      - name: NONMOTORIZED
        coefficient: 0.72
        alternatives:
          - WALK
          - BIKE
      - name: TRANSIT
        coefficient:  0.72
        alternatives:
            - name: WALKACCESS
              coefficient: 0.5
              alternatives:
              - WALK_LOC
              - WALK_PRM
              - WALK_MIX
            - name: PNRACCESS
              coefficient: 0.5
              alternatives:
              - PNR_LOC
              - PNR_PRM
              - PNR_MIX
            - name: KNRACCESS
              coefficient: 0.5
              alternatives:
              - KNR_LOC
              - KNR_PRM
              - KNR_MIX
      - name: SCHOOL_BUS
        coefficient: 0.72
        alternatives:
          - SCHOOLBUS
      - name: RIDEHAIL
        coefficient: 0.36
        alternatives:
          - TAXI
          - TNC_SINGLE
          - TNC_SHARED

CONSTANTS:
  orig_col_name: origin
  dest_col_name: destination
  costPerMile: 18.29
  costShareSr2: 1.75
  costShareSr3: 2.50
  waitThresh: 10.00
  walkThresh: 1.00
  shortWalk: 0.333
  longWalk: 0.667
  walkSpeed: 3.00
  bikeThresh: 6.00
  bikeSpeed: 12.00
#    maxCbdAreaTypeThresh: 2
#    indivTour: 1.00000
#    upperEA: 5
#    upperAM: 10
#    upperMD: 15
#    upperPM: 19
  I_MODE_MAP:
    DRIVEALONE: 1
    SHARED2: 2
    SHARED3: 3
    WALK: 4
    BIKE: 5
    WALK_LOC: 6
    WALK_PRM: 7
    WALK_MIX: 8
    PNR_LOC: 9
    PNR_PRM: 10
    PNR_MIX: 11
    KNR_LOC: 12
    KNR_PRM: 13
    KNR_MIX: 14
    SCHOOLBUS: 15
    TAXI: 16
    TNC_SINGLE: 17
    TNC_SHARED: 18
  I_SOV_MODES: [1]
  I_SR2_MODES: [2]
  I_SR3P_MODES: [3]
  I_AUTO_MODES: [1, 2, 3]
  I_WALK_MODE: 4
  I_BIKE_MODE: 5
  I_WALK_TRANSIT_MODES: [6,7,8]
  I_DRIVE_TRANSIT_MODES: [9,10,11,12,13,14]
  I_PNR_TRANSIT_MODES: [9,10,11]
  I_KNR_TRANSIT_MODES: [12,13,14]
  I_SCHOOLBUS_MODE: [15]
  I_RIDE_HAIL_MODES: [16, 17, 18]
  # RIDEHAIL Settings
  Taxi_baseFare: 2.20
  Taxi_costPerMile: 2.30
  Taxi_costPerMinute: 0.10
  Taxi_waitTime_mean:
    1: 5.5
    2: 9.5
    3: 13.3
    4: 17.3
    5: 26.5
  Taxi_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_single_baseFare: 2.20
  TNC_single_costPerMile: 1.33
  TNC_single_costPerMinute: 0.24
  TNC_single_costMinimum: 7.20
  TNC_single_waitTime_mean:
    1: 3.0
    2: 6.3
    3: 8.4
    4: 8.5
    5: 10.3
  TNC_single_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  TNC_shared_baseFare: 2.20
  TNC_shared_costPerMile: 0.53
  TNC_shared_costPerMinute: 0.10
  TNC_shared_costMinimum: 3.00
  TNC_shared_IVTFactor: 1.5
  TNC_shared_waitTime_mean:
    1: 5.0
    2: 8.0
    3: 11.0
    4: 15.0
    5: 15.0
  TNC_shared_waitTime_sd:
    1: 0
    2: 0
    3: 0
    4: 0
    5: 0
  min_waitTime: 0
  max_waitTime: 50

# so far, we can use the same spec as for non-joint tours
preprocessor:
  SPEC: trip_mode_choice_annotate_trips_preprocessor
  DF: df
  TABLES:
    - land_use
    - tours

#  - SPEC: trip_mode_choice_annotate_trips_preprocessor2
#    DF: df
#    TABLES:
#      - land_use

# to reduce memory needs filter chooser table to these fields
TOURS_MERGED_CHOOSER_COLUMNS:
  - hhsize
  - age
  - auto_ownership
  - number_of_participants
  - tour_category
  - parent_tour_id
  - tour_mode
  - duration
  - value_of_time
  - tour_type
  - free_parking_at_work


MODE_CHOICE_LOGSUM_COLUMN_NAME: mode_choice_logsum
