CONSTANTS:
  FULL: 1
  PART: 2
  UNIVERSITY: 3
  NONWORK: 4
  RETIRED: 5
  DRIVING: 6
  SCHOOL: 7
  PRESCHOOL: 8

annotate_persons:
  SPEC: annotate_persons_cdap
  DF: persons


annotate_households:
  SPEC: annotate_households_cdap
  DF: households
  TABLES:
    - persons
