
inherit_settings: True

multiprocess: False
mem_tick: 30
profile: False
strict: False
num_processes: 1

households_sample_size:  0
chunk_size: 0

# - tracing
trace_hh_id:
trace_od:

resume_after: trip_mode_choice

models:
  - write_data_dictionary
  - write_tables

output_tables:
  action: include
  prefix: final_
  tables:
    - checkpoints
#    - accessibility
#    - land_use
#    - households
#    - persons
#    - trips
#    - tours


coalesce:
  names:
    - output_0/pipeline.h5
    - output_1/pipeline.h5
  slice:
    tables:
      - households
      - persons
