name: ActivitySim Docs

on:
  push:
    branches: [ main, develop, sharrow-black ]
  workflow_dispatch:

jobs:
  docbuild:
    if: ${{ github.repository }} == "camsys/activitysim"
    name: ubuntu-latest py3.9
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          environment-file: conda-environments/docbuild.yml
          python-version: 3.9
          activate-environment: docbuild
          auto-activate-base: false
          auto-update-conda: false
      - name: Install activitysim
        run: |
          python -m pip install -e .
      - name: Conda checkup
        run: |
          conda info -a
          conda list
          echo ${{ github.repository }}
      - name: Build the docs
        run: |
          cd docs
          make clean
          make html
      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Token is created automatically by Github Actions, no other config needed
          publish_dir: ./docs/_build/html
          destination_dir: bleed
